
FROM ubuntu:latest

LABEL author="Chandan Goswami " email="goswami75@gmail.com"
LABEL version="0.2"

RUN apt update &&\
    apt install -y nodejs && \  
    apt install -y npm && \  
    apt install -y tar 

CMD [ "tail", "-f", "/dev/null" ]
