version: "3"
services:
  spark-master:
    image: integra/spark-master:latest
    ports:
      - "4040:4040"
      - "9090:8080"
      - "7077:7077"
      - "8889:8889"
    networks:
      - INTG_NW
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ../compute/:/opt/compute

    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker:
    image: integra/spark-worker:latest
    networks:
      - INTG_NW
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data

networks:
  INTG_NW:
    driver: bridge
