# Base image
FROM ubuntu:latest

# Install Java
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y openssh-server && \
    apt-get install -y vim && \
    apt-get install -y net-tools && \
    apt-get clean 

# Configure SSH for Password less Login - basic pre-requisite for Hadoop cluster
RUN mkdir /var/run/sshd && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/^#?PasswordAuthentication\s+.*/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -ri 's/^#?ChallengeResponseAuthentication\s+.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

# Add Hadoop user
RUN useradd -ms /bin/bash hadoop

# Install Hadoop
RUN wget -q https://archive.apache.org/dist/hadoop/common/hadoop-3.2.2/hadoop-3.2.2.tar.gz 

RUN tar -xzf hadoop-3.2.2.tar.gz -C /home/hadoop 


# Configure passWd less login
RUN mkdir -p /home/hadoop/.ssh && \
    ssh-keygen -f /home/hadoop/.ssh/id_rsa -N '' && \
    cp /home/hadoop/.ssh/id_rsa.pub /home/hadoop/.ssh/authorized_keys && \
    echo "Host * " > /home/hadoop/.ssh/config && \
    echo "    StrictHostKeyChecking no " >> /home/hadoop/.ssh/config && \
    chmod -R 755 /home/hadoop && \
    chmod 750 /home/hadoop/.ssh && \
    chmod 600 /home/hadoop/.ssh/id_rsa 
    
# Set Java home
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

# Configure Hadoop environment variables
ENV HADOOP_HOME /home/hadoop/hadoop-3.2.2
ENV PATH $PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
ENV HADOOP_CONF_DIR $HADOOP_HOME/etc/hadoop
ENV HDFS_NAMENODE_USER hadoop
ENV HDFS_DATANODE_USER hadoop
ENV HDFS_SECONDARYNAMENODE_USER hadoop
ENV YARN_RESOURCEMANAGER_USER hadoop
ENV YARN_NODEMANAGER_USER hadoop

# Copy Hadoop configuration files
 COPY config/core-site.xml $HADOOP_CONF_DIR/
 COPY config/hdfs-site.xml $HADOOP_CONF_DIR/
 COPY config/mapred-site.xml $HADOOP_CONF_DIR/
 COPY config/yarn-site.xml $HADOOP_CONF_DIR/
 COPY config/workers $HADOOP_CONF_DIR/
 COPY config/hadoop-env.sh $HADOOP_CONF_DIR/
 COPY config/remcp.sh $HADOOP_CONF_DIR/
 COPY config/.bashrc /home/hadoop/
 COPY config/remhost.sh $HADOOP_CONF_DIR/

RUN chown -R hadoop:hadoop /home/hadoop

# Expose Hadoop ports
EXPOSE 9000 9870 8088

# Set the entry point to start the SSH server
CMD ["/usr/sbin/sshd", "-D"]

