version: '3.0' 

services:
  nameNode:
    image: hadoop_img:latest
    hostname: nameNode
    ports:
      - "2022:22"
      - "8080:8080"
      - "9000:9000"
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./data:/opt/hadoop/data
    environment:
      - HADOOP_HOME /home/hadoop/hadoop-3.2.2
      - PATH $PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
      - HADOOP_CONF_DIR $HADOOP_HOME/etc/hadoop
      - HDFS_NAMENODE_USER hadoop
      - HDFS_DATANODE_USER hadoop
      - HDFS_SECONDARYNAMENODE_USER hadoop
      - YARN_RESOURCEMANAGER_USER hadoop
      - YARN_NODEMANAGER_USER hadoop
    networks:
      - INTG_NW

  dataNode:
    image: hadoop_img:latest
    depends_on:
      - nameNode
    volumes:
      - ./data:/opt/hadoop/data
    environment:
      - HADOOP_HOME /home/hadoop/hadoop-3.2.2
      - PATH $PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
      - HADOOP_CONF_DIR $HADOOP_HOME/etc/hadoop
      - HDFS_NAMENODE_USER hadoop
      - HDFS_DATANODE_USER hadoop
      - HDFS_SECONDARYNAMENODE_USER hadoop
      - YARN_RESOURCEMANAGER_USER hadoop
      - YARN_NODEMANAGER_USER hadoop
    networks:
      - INTG_NW

networks:
  INTG_NW:
    driver: bridge

