version: '3.0' 

services:
  nameNode:
    image: hadoop_img:latest
    hostname: nameNode
    ports:
      - "2022:22"
      - "8080:8080"
      - "9000:9000"
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./data:/opt/hadoop/data
      - ./app:/opt/hadoop/app
    networks:
      - INTG_NW

  dataNode:
    image: hadoop_img:latest
    depends_on:
      - nameNode
    volumes:
      - ./data:/opt/hadoop/data
      - ./app:/opt/hadoop/app
    networks:
      - INTG_NW

  sftp:
    image: goswami75/mysftp:latest
    depends_on:
      - nameNode
    volumes:
      - ./data:/opt/hadoop/data
    ports:
      - "2023:22"
    networks:
      - INTG_NW

networks:
  INTG_NW:
    driver: bridge

